name: Deploy to GitHub pages
permissions:
  contents: write
on:
  push:
    branches: [main]
env:
  BUILD_FOLDER: .output/public # or .output/public/yourrepositoryname/
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRUNCH: gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate static Nuxt 3 files
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: 'npm'

      - run: |
          npm install
          npm generate
          touch ./.output/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{env.BUILD_FOLDER}}
          branch: ${{env.BRANCH}}
